#3721: WinCE: MIDlet install shows "null needs to check for features specific to your phone." and does not start midlet
Fix odd linking error:

c:\cactusjack\ccp\phoneme_feature\midp\src\highlevelui\wince_application
\reference\native\winceapp_export.cpp(199) : error C2733: second C linkage
of overloaded function 'JVMSPI_SetSystemProperty' not allowed